# Generated by Django 2.2.11 on 2020-03-15 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200315_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='new_field',
            field=models.CharField(default=1, max_length=123),
            preserve_default=False,
        ),
    ]
