# Generated by Django 2.2.11 on 2020-03-15 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_new_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='new_field',
        ),
        migrations.RemoveField(
            model_name='post',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
